screen_capture:
  display_popup_size: 660x500
  text_width: 27
  font_size: 12
  translate_button: s
  output_filename: tmp.png

text_detection:
  backend: Google
  #  backend: api8
  language: jpn

text_translation:
  backend: Google
  location: 'us-central1'
  src_language: ja
  src_word_split: ''
  target_language: zh-TW
  target_word_split: ''
